# Generated by Django 4.2.20 on 2025-04-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studychatbox',
            name='bot_response',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='studychatbox',
            name='user_message',
            field=models.TextField(),
        ),
    ]
